'use client';
import React,{useEffect} from 'react';
import {toast as showToast} from 'sonner';
import {Toaster} from '@/components/ui/sonner';
import {AppContext,useAppModel,useApp,initials} from './model';
import {Button,Icon} from './ui';
import Home from './Home';
import {SearchPage,ResultsPage} from './Search';
import Property from './Property';
import {RecentlyViewed,Compare} from './Collections';
import {Profile} from './Account';
import Dialogs from './Dialogs';
import WebTools from './WebTools';
import About from './About';
import {Contact,Privacy,Terms} from './PublicInfo';
import AccountAccess from './AccountAccess';
import {accessFor} from './accessPolicy.js';
const pages={home:Home,search:SearchPage,results:ResultsPage,map:ResultsPage,property:Property,recent:RecentlyViewed,compare:Compare,profile:Profile,about:About,contact:Contact,privacy:Privacy,terms:Terms,register:AccountAccess,login:AccountAccess,'verify-email':AccountAccess,'forgot-password':AccountAccess,'reset-password':AccountAccess};
function AccessNotice({access}){const {nav}=useApp();return <div className="narrow"><div className="page-head"><h1>{access==='checking'?'Checking your account…':access==='sign-in'?'Sign in to continue':'Not available yet'}</h1></div><div className="panel"><p>{access==='checking'?'Checking the account service for a valid session.':access==='sign-in'?'This feature requires a verified BalhinBalay account.':'This feature is not connected to an account-backed service yet. No changes can be saved or sent here.'}</p><div className="row wrap" style={{marginTop:16}}>{access==='sign-in'&&<Button onClick={()=>nav('login')}>Sign in</Button>}<Button className="secondary" onClick={()=>nav('search')}>Explore places</Button></div></div></div>;}
class ErrorBoundary extends React.Component {state={error:false};static getDerivedStateFromError(){return {error:true};}render(){if(this.state.error)return <main><div className="empty"><h1>This page could not be opened.</h1><p>Reload to reopen the beta.</p><Button onClick={()=>location.reload()}>Reload</Button></div></main>;return this.props.children;}}
function App(){const app=useAppModel();const {state,nav,patch,toast,account}=app;const active=['home','saved','profile'].includes(state.page)?state.page:['search','results','map','property','compare'].includes(state.page)?'search':'profile';const navItems=[['home','Home','home'],['search','Search','search'],['saved','Saved','heart'],['profile','Profile','user']];const Page=pages[state.page]||Home;const access=accessFor(state.page,account,app.sessionChecked);const unread=false;useEffect(()=>{if(toast)showToast(toast,{id:'balhinbalay-feedback',duration:3200});},[toast]);return <AppContext.Provider value={app}><header className="top"><div className="top-inner"><button className="brand" onClick={()=>nav('home')} aria-label="BalhinBalay home"><span className="brand-mark"><Icon name="home"/></span>BalhinBalay</button><div className="desktop-nav">{navItems.map(([p,n])=><button key={p} className={active===p?'active':''} onClick={()=>nav(p)} aria-current={active===p?'page':undefined}>{n}</button>)}</div><button className="icon-btn inbox-button" onClick={()=>nav('messages')} aria-label={'Messages'+(unread?', unread message':'')}><Icon name="message"/>{unread&&<span className="unread-dot"/>}</button><button className="avatar" onClick={()=>nav('profile')} aria-label="Your profile">{initials(account?.email)}</button></div></header><main id="app"><p className="notice preview-notice"><strong>Beta preview · Sample listings</strong><br/>Listings are illustrative. Compare and recently viewed stay on this device. Account registration, when available, stores your email and verification state on the account service. Saved items, messaging and listing publishing are unavailable.</p>{access==='public'?<Page key={state.page}/>:<AccessNotice access={access}/>}<footer className="site-footer"><div className="footer-links">{[['about','About'],['contact','Contact'],['privacy','Privacy'],['terms','Terms']].map(([page,label])=><button key={page} onClick={()=>nav(page)} aria-current={state.page===page?'page':undefined}>{label}</button>)}</div><span>Beta preview · Sample listings</span></footer></main><nav className="bottom-nav" aria-label="Main navigation">{navItems.map(([p,n,i])=><button key={p} className={active===p?'active':''} onClick={()=>nav(p)} aria-current={active===p?'page':undefined}><span className="nav-icon"><Icon name={i}/></span>{n}</button>)}</nav>{state.compare.length>0&&['results','recent','home'].includes(state.page)&&<div className="compare-tray"><span><strong>{state.compare.length}</strong> / 3 places selected</span><div className="row"><button onClick={()=>patch({compare:[]})} aria-label="Clear comparison"><Icon name="close"/></button><Button onClick={()=>nav('compare')}>Compare <Icon name="arrow"/></Button></div></div>}<Dialogs key={app.modal?.type+'-'+app.modal?.id}/><Toaster theme="light" position="bottom-center" toastOptions={{className:'bb-toast',unstyled:true}}/><WebTools/></AppContext.Provider>;}
export default function BalhinBalay(){return <ErrorBoundary><App/></ErrorBoundary>;}
