'use client';
import React,{useEffect} from 'react';
import {toast as showToast} from 'sonner';
import {Toaster} from '@/components/ui/sonner';
import {AppContext,useAppModel,initials} from './model';
import {Button,Icon} from './ui';
import Home from './Home';
import {SearchPage,ResultsPage} from './Search';
import Property from './Property';
import {Saved,Compare,Messages,Chat} from './Collections';
import {Profile,EditProfile,Settings,Owner,Editor} from './Account';
import Dialogs from './Dialogs';
import WebTools from './WebTools';
import About from './About';
import {Contact,Privacy,Terms} from './PublicInfo';
import AccountAccess from './AccountAccess';
const pages={home:Home,search:SearchPage,results:ResultsPage,map:ResultsPage,property:Property,saved:Saved,compare:Compare,messages:Messages,chat:Chat,profile:Profile,editProfile:EditProfile,settings:Settings,owner:Owner,editor:Editor,about:About,contact:Contact,privacy:Privacy,terms:Terms,register:AccountAccess,login:AccountAccess,'verify-email':AccountAccess,'forgot-password':AccountAccess,'reset-password':AccountAccess};
class ErrorBoundary extends React.Component {state={error:false};static getDerivedStateFromError(){return {error:true};}render(){if(this.state.error)return <main><div className="empty"><h1>This page could not be opened.</h1><p>Reload to reopen your saved demo.</p><Button onClick={()=>location.reload()}>Reload</Button></div></main>;return this.props.children;}}
function App(){const app=useAppModel();const {db,state,nav,patch,toast,account}=app;const active=['home','saved','profile'].includes(state.page)?state.page:['search','results','map','property','compare'].includes(state.page)?'search':'profile';const navItems=[['home','Home','home'],['search','Search','search'],['saved','Saved','heart'],['profile','Profile','user']];const Page=pages[state.page]||Home;const unread=db.convos.some(c=>c.unread);useEffect(()=>{if(toast)showToast(toast,{id:'balhinbalay-feedback',duration:3200});},[toast]);return <AppContext.Provider value={app}><header className="top"><div className="top-inner"><button className="brand" onClick={()=>nav('home')} aria-label="BalhinBalay home"><span className="brand-mark"><Icon name="home"/></span>BalhinBalay</button><div className="desktop-nav">{navItems.map(([p,n])=><button key={p} className={active===p?'active':''} onClick={()=>nav(p)} aria-current={active===p?'page':undefined}>{n}</button>)}</div><button className="icon-btn inbox-button" onClick={()=>nav('messages')} aria-label={'Messages'+(unread?', unread message':'')}><Icon name="message"/>{unread&&<span className="unread-dot"/>}</button><button className="avatar" onClick={()=>nav('profile')} aria-label="Your profile">{initials(account?.email||db.profile.name)}</button></div></header><main id="app"><p className="notice preview-notice"><strong>Beta preview · Sample listings</strong><br/>Listings and messages are illustrative. Their demo changes stay on this device. Account registration, when available, stores your email and verification state securely on the account service. Do not enter private information in listing previews.</p><Page key={state.page==='editor'?state.draft?.id||'new':state.page}/><footer className="site-footer"><div className="footer-links">{[['about','About'],['contact','Contact'],['privacy','Privacy'],['terms','Terms']].map(([page,label])=><button key={page} onClick={()=>nav(page)} aria-current={state.page===page?'page':undefined}>{label}</button>)}</div><span>Beta preview · Sample listings</span></footer></main><nav className="bottom-nav" aria-label="Main navigation">{navItems.map(([p,n,i])=><button key={p} className={active===p?'active':''} onClick={()=>nav(p)} aria-current={active===p?'page':undefined}><span className="nav-icon"><Icon name={i}/></span>{n}</button>)}</nav>{state.compare.length>0&&['results','saved','home'].includes(state.page)&&<div className="compare-tray"><span><strong>{state.compare.length}</strong> / 3 places selected</span><div className="row"><button onClick={()=>patch({compare:[]})} aria-label="Clear comparison"><Icon name="close"/></button><Button onClick={()=>nav('compare')}>Compare <Icon name="arrow"/></Button></div></div>}<Dialogs key={app.modal?.type+'-'+app.modal?.id}/><Toaster theme="light" position="bottom-center" toastOptions={{className:'bb-toast',unstyled:true}}/><WebTools/></AppContext.Provider>;}
export default function BalhinBalay(){return <ErrorBoundary><App/></ErrorBoundary>;}
