'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Button} from './ui';
import {marketplaceRequest} from './Marketplace';
const errorText=cause=>cause.code==='UNAUTHENTICATED'?'Your session has ended. Sign in again.':cause.message||'Messages could not be reached. Try again.';
const css='.message-compose{display:grid;gap:12px}.message-compose textarea{display:block;width:100%;min-height:110px;padding:10px;border:1px solid #ccd3d7;border-radius:8px;font:inherit}.messaging-list{display:grid;gap:14px}';
const date=value=>new Date(value).toLocaleString();
function ErrorNotice({error}){return error&&<p role="alert" className="marketplace-error">{error}</p>;}
export function Messages(){
  const [items,setItems]=useState([]),[next,setNext]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const load=async(more=false)=>{setLoading(true);setError('');try{const result=await marketplaceRequest('conversations'+(more?'?before='+encodeURIComponent(next):''));setItems(old=>more?[...old,...result.conversations]:result.conversations);setNext(result.next_cursor);}catch(cause){setError(errorText(cause));}finally{setLoading(false);}};
  useEffect(()=>{let active=true;marketplaceRequest('conversations').then(result=>{if(active){setItems(result.conversations);setNext(result.next_cursor);}}).catch(cause=>{if(active)setError(errorText(cause));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  return <div className="narrow"><style>{css}</style><div className="page-head"><h1>Messages</h1><Button className="secondary" disabled={loading} onClick={()=>load()}>Refresh</Button></div><ErrorNotice error={error}/>{loading&&!items.length?<p role="status">Loading conversations…</p>:!error&&!items.length?<div className="panel"><p>No conversations yet.</p><p>Sample listings cannot start a conversation.</p></div>:null}<div className="messaging-list">{items.map(c=><article className="panel" key={c.id}><h2><Link href={'/chat/'+c.id}>{c.listing_context.title||'Listing conversation'}</Link></h2><p>{c.listing_context.property_type} · {c.listing_context.transaction_type}</p><p>{c.participants.filter(p=>p.id!==c.own_participant_id).map(p=>p.label).join('')} · {date(c.updated_at)}</p>{!c.can_send&&<p>Messages paused. You can still read this conversation.</p>}</article>)}</div>{next&&<Button disabled={loading} onClick={()=>load(true)}>Load more conversations</Button>}</div>;
}
export function Chat({conversationId}){
  const [conversation,setConversation]=useState(null),[messages,setMessages]=useState([]),[next,setNext]=useState(null),[text,setText]=useState(''),[request,setRequest]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false);
  const reload=async()=>{setLoading(true);setError('');try{const [a,b]=await Promise.all([marketplaceRequest('conversations/'+conversationId),marketplaceRequest('conversations/'+conversationId+'/messages')]);setConversation(a.conversation);setMessages(b.messages);setNext(b.next_cursor);}catch(cause){setError(errorText(cause));}finally{setLoading(false);}};
  useEffect(()=>{let active=true;Promise.all([marketplaceRequest('conversations/'+conversationId),marketplaceRequest('conversations/'+conversationId+'/messages')]).then(([a,b])=>{if(active){setConversation(a.conversation);setMessages(b.messages);setNext(b.next_cursor);}}).catch(cause=>{if(active)setError(errorText(cause));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[conversationId]);
  const more=async()=>{setLoading(true);setError('');try{const result=await marketplaceRequest('conversations/'+conversationId+'/messages?before='+encodeURIComponent(next));setMessages(old=>[...result.messages,...old]);setNext(result.next_cursor);}catch(cause){setError(errorText(cause));}finally{setLoading(false);}};
  const send=async e=>{e.preventDefault();if(sending||!conversation?.can_send||!text.trim())return;const payload=request?.body===text?request:{body:text,client_request_id:crypto.randomUUID()};setRequest(payload);setSending(true);setError('');try{const result=await marketplaceRequest('conversations/'+conversationId+'/messages',{method:'POST',body:payload});setMessages(old=>old.some(m=>m.id===result.message.id)?old:[...old,result.message]);setText('');setRequest(null);}catch(cause){setError(errorText(cause));if(cause.code==='CONVERSATION_FROZEN')setConversation(old=>({...old,can_send:false}));}finally{setSending(false);}};
  return <div className="narrow"><style>{css}</style><Link href="/messages">Back to Messages</Link><div className="page-head"><h1>{conversation?.listing_context.title||'Conversation'}</h1><Button className="secondary" disabled={loading||sending} onClick={reload}>Refresh</Button></div><ErrorNotice error={error}/>{loading&&!conversation&&<p role="status">Loading conversation…</p>}{conversation&&<><p>{conversation.listing_context.property_type} · {conversation.listing_context.transaction_type}</p>{next&&<Button disabled={loading||sending} onClick={more}>Load earlier messages</Button>}<div aria-label="Conversation messages">{!messages.length&&!loading&&<p>No messages in this conversation.</p>}{messages.map(m=><article key={m.id} className="panel"><p><strong>{m.sender_label}</strong>{m.sender_participant_id===conversation.own_participant_id?' · You':''} · <time dateTime={m.created_at}>{date(m.created_at)}</time></p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{m.body}</p></article>)}</div>{!conversation.can_send&&<p role="status">Messages are paused while the original Lister access is inactive. History remains readable. Refresh to check whether access has been restored.</p>}<form className="message-compose" onSubmit={send}><label className="field">Message<textarea aria-label="Message" value={text} onChange={e=>setText(e.target.value)} maxLength={2000} disabled={sending||!conversation.can_send}/></label><Button type="submit" disabled={sending||loading||!conversation.can_send||!text.trim()}>{sending?'Sending…':'Send message'}</Button></form></>}</div>;
}
