import React from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {NativeSelect} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {icons} from './data';
import {useApp,money,img,distance} from './model';
import {schools} from './data';
import {handleListingImageError} from './imageFallback';
export const ListingImage = ({alt,...props}) => <img {...props} alt={alt} onError={handleListingImageError}/>;
export const Icon = ({name}) => <svg className="icon" viewBox="0 0 24 24" aria-hidden="true"><path d={icons[name] || icons.home}/></svg>;
export const Button = ({children,icon,className='',...props}) => <button type="button" className={'btn '+className} {...props}>{icon&&<Icon name={icon}/>} {children}</button>;
export function TabBar({items,value,onChange}) {return <Tabs className="bb-tabs" value={value} onValueChange={onChange}><TabsList className="tabs" aria-label="Choose a view">{items.map(item=>{const [name,icon,count]=Array.isArray(item)?item:[item];return <TabsTrigger key={name} value={name} className={value===name?'active':''}>{icon&&<Icon name={icon}/>} {name}{count!==undefined&&<span className="count">{count}</span>}</TabsTrigger>;})}</TabsList></Tabs>;}
export const Field = ({label,name,value,onChange,...props}) => <label className="field"><span>{label}</span><input name={name} value={value??''} onChange={onChange} {...props}/></label>;
export const Select = ({label,name,options,value,onChange,...props}) => <label className="field"><span>{label}</span><NativeSelect name={name} value={value} onChange={onChange} {...props}>{options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return <option key={v} value={v}>{t}</option>;})}</NativeSelect></label>;
export const Check = ({label,checked,onChange,...props}) => <label className="checkline"><Checkbox className="bb-check" checked={checked} onCheckedChange={onChange} {...props}/>{label}</label>;
export function Back({label='Back',page='home'}) {const {nav}=useApp();return <button className="back" onClick={()=>nav(page)}><Icon name="back"/>{label}</button>;}
export function Empty({title,copy,label='Explore places',onClick}) {const {nav}=useApp();return <div className="empty"><Icon name="search"/><h2>{title}</h2><p>{copy}</p><Button onClick={onClick||(()=>nav('search'))}>{label}</Button></div>;}
export function Segment(){const {state,setQuery}=useApp();return <div className="segment" role="group" aria-label="Rent or buy">{['Rent','Buy'].map(mode=><button type="button" key={mode} className={state.q.mode===mode?'active':''} aria-pressed={state.q.mode===mode} onClick={()=>setQuery({mode})}>{mode}</button>)}</div>;}
export function PropertyCard({p}) {const {db,state,openProperty,toggleSave,compare}=useApp();const saved=db.saved.includes(p.id),selected=state.compare.includes(p.id);return <article className="property-card"><div className="media"><button onClick={()=>openProperty(p.id)} aria-label={'View '+p.title}><ListingImage src={img(p)} alt={'Illustrative '+p.type.toLowerCase()+' interior'} loading="lazy"/></button><span className="badge">For {p.mode==='Rent'?'rent':'sale'}</span><button className={'heart '+(saved?'saved':'')} onClick={()=>toggleSave(p.id)} aria-label={(saved?'Unsave ':'Save ')+p.title} aria-pressed={saved}><Icon name="heart"/></button></div><div className="card-body"><div className="price">{money(p.price)} {p.mode==='Rent'&&<small>/ month</small>}</div><button className="card-title" onClick={()=>openProperty(p.id)}>{p.title}</button><p className="location">{p.area}, {p.city}</p><div className="facts"><span><Icon name="bed"/>{p.beds||'Studio'}{p.beds?' bed'+(p.beds>1?'s':''):''}</span><span><Icon name="bath"/>{p.baths} bath{p.baths>1?'s':''}</span><span><Icon name="size"/>{p.size} m²</span></div><div className="card-foot"><span className="micro muted">{p.type}{state.q.method==='School'?' · '+distance(p,schools[state.q.school]).toFixed(1)+' km to campus':''}</span><button className={'compare-btn '+(selected?'active':'')} onClick={()=>compare(p.id)} aria-pressed={selected}><Icon name={selected?'check':'plus'}/>Compare</button></div></div></article>;}
export function Mini({p,onClick}){const {openProperty}=useApp();return <button className="mini-card" onClick={onClick||(()=>openProperty(p.id))}><ListingImage src={img(p)} alt="Illustrative property photo"/><span className="grow"><span className="price">{money(p.price)} {p.mode==='Rent'&&<small>/ mo</small>}</span><span className="mini-title">{p.title}</span><span className="mini-location">{p.area}, {p.city}</span></span><Icon name="chevron"/></button>;}
